### ISSUE TITLE
Validating Asset Speed

### ISSUE THREAD

**Issue by Aerovium** [ModRealms-Network/ModRealmsLauncher#1]
When I click play, it takes around 30~60 seconds on most attempts to get past the "validating asset integrity". This feels abnormally slow and I was recommended to make the issue clear here, this does not happen on other launchers so I can only assume it's a launcher issue.

**Comment by TheFlash787** [comment]
As of https://github.com/ModRealms-Network/ModRealmsLauncher/releases/tag/v2.2.0-release, this has now been fixed.

Resolved. ❤️
