### ISSUE TITLE
Is there an error message if (somehow) the loading screen glitches out and errors?

### ISSUE THREAD

**Issue by MatthyPlayz** [ModRealms-Network/ModRealmsLauncher#3]
Title says most of it.
As in the "loading screen", I basically mean "the-completely-blank-except-for-the-spinning-modrealms-launcher screen"

**Comment by TheFlash787** [comment]
Hey!

I'm not too sure what you mean by 'loading screen glitches out and errors'.

If it errors, I assume that it would print an error message. However, if there is an issue with the downloading of the distribution file upon startup, there will be an error message that shows. Although, if you have a local version that can be used, your launcher will start up but will notify you about that.

I'm going to close the issue with the answer being yes. 😄 
Thank you!
